### ISSUE TITLE
Can't build the cliqz concept browser.

### ISSUE THREAD

**Issue by cnevinc** [cliqz/cliqz-concept-browser#24]
### Steps to reproduce
I can't build the cliqz concept browser... I guess my ReactNative version is not correct?
For example `BridgePackage` didn't implement some abstract method... and `ReactInstanceManager` in `ReactHost.kt` can't resolve `setJSMainModulePath(..)` 
I  just checked the latest ReactNativeAndroid [source code but the method is there](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManagerBuilder.java) 
I also checked my local RN is the latest 0.20.1.
Is that correct? Thank you!
### Expected behavior
-

### Actual behavior
-

### Device information

* Android device:  API 28
* Reference Browser version: the one on master

**Comment by sammacbeth** [comment]
Hi. You have to run the following commands to get the correct ReactNative version:
```bash
cd cliqzSearch
npm ci
npm run build
```
Let me know if that gets it building.

**Comment by cnevinc** [comment]
Fixed! Thank you!
